-- Add missing columns to games table
ALTER TABLE games ADD COLUMN IF NOT EXISTS publisher TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS release_date TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS percentage INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS days_played INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS minutes_played INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS console TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS store TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS price DECIMAL(10,2) DEFAULT 0;
